export const LOAD_SERVER_STATUS_SUCCESS = 'LOAD_SERVER_STATUS_SUCCESS';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const SEND_USER_FORM_SUCCESS = 'SEND_USER_FORM_SUCCESS';
export const SEND_USER_FORM_ERROR = 'SEND_USER_FORM_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';

export const LOAD_PASSWORD_PAGE = 'LOAD_PASSWORD_PAGE';
export const REQUEST_PASSWORD_SUCCESS = 'REQUEST_PASSWORD_SUCCESS';
export const REQUEST_PASSWORD_ERROR = 'REQUEST_PASSWORD_ERROR';
export const SEND_USER_UPDATE_PASS_SUCCESS = 'SEND_USER_UPDATE_PASS_SUCCESS';
export const SEND_USER_UPDATE_PASS_ERROR = 'SEND_USER_UPDATE_PASS_ERROR';
export const SHOW_USER_LOGINS_SUCCESS = 'SHOW_USER_LOGINS_SUCCESS';
export const SHOW_USER_LOGINS_ERROR = 'SHOW_USER_LOGINS_ERROR';

export const LOAD_SPECIES_SUCCESS = 'LOAD_SPECIES_SUCCESS';

export const SEND_ANIMAL_FORM_SUCCESS = 'SEND_ANIMAL_FORM_SUCCESS';
export const SEND_ANIMAL_FORM_ERROR = 'SEND_ANIMAL_FORM_ERROR';
export const CANCEL_ANIMAL_FORM = 'CANCEL_ANIMAL_FORM';
export const SHOW_ANIMAL_PROFILE = 'SHOW_ANIMAL_PROFILE';
export const SHOW_ANIMAL_PROFILE_IMAGES_SUCCESS = 'SHOW_ANIMAL_PROFILE_IMAGES_SUCCESS';
export const SHOW_ANIMAL_PROFILE_IMAGES_ERROR = 'SHOW_ANIMAL_PROFILE_IMAGES_ERROR';
export const UPLOAD_IMAGE_ANIMAL_SUCCESS = 'UPLOAD_IMAGE_ANIMAL_SUCCESS';
export const UPLOAD_IMAGE_ANIMAL_ERROR = 'UPLOAD_IMAGE_ANIMAL_ERROR';
export const REMOVE_IMAGE_ANIMAL_SUCCESS = 'REMOVE_IMAGE_ANIMAL_SUCCESS';
export const REMOVE_IMAGE_ANIMAL_ERROR = 'REMOVE_IMAGE_ANIMAL_ERROR';
export const LOAD_ANIMALS_SUCCESS = 'LOAD_ANIMALS_SUCCESS';
export const LOAD_ANIMALS_ERROR = 'LOAD_ANIMALS_ERROR';
export const CLEAN_ANIMALS_SUCCESS = 'CLEAN_ANIMALS_SUCCESS';
export const SEARCH_ANIMALS_START = 'SEARCH_ANIMALS_START';
export const SEARCH_ANIMALS_SUCCESS = 'SEARCH_ANIMALS_SUCCESS';
export const SEARCH_ANIMALS_ERROR = 'SEARCH_ANIMALS_ERROR';
export const EDIT_ANIMAL_SUCCESS = 'EDIT_ANIMAL_SUCCESS';
export const EDIT_ANIMAL_ERROR = 'EDIT_ANIMAL_ERROR';

export const SEND_EVENT_FORM_SUCCESS = 'SEND_EVENT_FORM_SUCCESS';
export const SEND_EVENT_FORM_ERROR = 'SEND_EVENT_FORM_ERROR';
export const CANCEL_EVENT_FORM = 'CANCEL_EVENT_FORM';
export const UPLOAD_IMAGE_EVENT_ERROR = 'UPLOAD_IMAGE_EVENT_ERROR';
export const UPLOAD_IMAGE_EVENT_SUCCESS = 'UPLOAD_IMAGE_EVENT_SUCCESS';
export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
export const SHOW_EVENT_SUCCESS = 'SHOW_EVENT_SUCCESS';
export const CLEAN_EVENTS_SUCCESS = 'CLEAN_EVENTS_SUCCESS';
export const SEARCH_EVENTS_START = 'SEARCH_EVENTS_START';
export const SEARCH_EVENTS_SUCCESS = 'SEARCH_EVENTS_SUCCESS';
export const SEARCH_EVENTS_ERROR = 'SEARCH_EVENTS_ERROR';

export const CONFIRM_OPEN = 'CONFIRM_OPEN';

export const EXPORT_ANIMALS_XLS = 'EXPORT_ANIMALS_XLS';
export const EXPORT_ANIMAL_PDF = 'EXPORT_ANIMAL_PDF';
export const EXPORT_ANIMAL_EVENT = 'EXPORT_ANIMAL_EVENT';
export const EXPORT_ANIMALS_XLS_START = 'EXPORT_ANIMALS_XLS_START';
export const EXPORT_ANIMAL_PDF_START = 'EXPORT_ANIMAL_PDF_START';
export const EXPORT_ANIMAL_EVENT_START = 'EXPORT_ANIMAL_EVENT_START';

export const SEND_ADOPTER_FORM_SUCCESS = 'SEND_ADOPTER_FORM_SUCCESS';
export const SEND_ADOPTER_FORM_ERROR = 'SEND_EVENT_FORM_ERROR';
export const CANCEL_ADOPTER_FORM = 'CANCEL_ADOPTER_FORM';
export const LOAD_ADOPTERS_SUCCESS = 'LOAD_ADOPTERS_SUCCESS';
export const CLEAN_ADOPTERS_SUCCESS = 'CLEAN_ADOPTERS_SUCCESS';
export const SHOW_ADOPTER_PROFILE = 'SHOW_ADOPTER_PROFILE';
