export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_SERVER_STATUS_SUCCESS = 'LOAD_SERVER_STATUS_SUCCESS';
export const LOGIN_USER_SUCCES = 'LOGIN_USER_SUCCES';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
